[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "crypto"
path = "src/lib.rs"

[dependencies]
rand = "0.8.5"
sha3 = "0.10.8"
secp256k1 = "0.27.0"
hex = "0.4.3"
bip39 = "2.0.0"