name: KMM CI

on: [push, pull_request]

jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Android and shared code
        run: ./gradlew build

      - name: Run Android and shared tests
        run: ./gradlew test

  ios_build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Cache CocoaPods
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('/Users/usman/StudioProjects/speech/speech/vaultIos/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: pod install --project-directory=/Users/usman/StudioProjects/speech/speech/vaultIos

      - name: Build iOS app
        run: xcodebuild -workspace /Users/usman/StudioProjects/speech/speech/vaultIos/iosApp.xcworkspace -scheme iosApp -configuration Release build | xcpretty

      - name: Run iOS tests
        run: xcodebuild test -workspace /Users/usman/StudioProjects/speech/speech/vaultIos/iosApp.xcworkspace -scheme iosApp -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' | xcpretty
