name: Build Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'

      - name: Setup Xcode 13.0
        uses: xcpretty/xcode-action@v3.7.0
        with:
          xcode-version: '13.0'

      - name: Build
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: MyApp.ipa
          path: iosApp/build/outputs/ipa/myApp.ipa

